version: '2'

# networks:
#   app-tier:
#     driver: bridge

services:
  mysql:
    image: 'bitnami/mysql:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
    # networks:
    #   - app-tier
    # myapp:
    #   image: 'YOUR_APPLICATION_IMAGE'
    #   networks:
    #     - app-tier
