-- Active: 1729814945779@@127.0.0.1@3306@spring_batch
delete from `BATCH_STEP_EXECUTION_SEQ`

delete from `BATCH_STEP_EXECUTION_CONTEXT`

delete from `BATCH_STEP_EXECUTION`

delete from `BATCH_JOB_SEQ`

delete from `BATCH_JOB_EXECUTION_SEQ`

delete from `BATCH_JOB_INSTANCE`

delete from `BATCH_JOB_EXECUTION_PARAMS`

delete from `BATCH_JOB_EXECUTION_CONTEXT`

delete from `BATCH_JOB_EXECUTION`